[package]
name = "rocket"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]

[dependencies]
itertools = "*"
piston = "0.10.0"
piston2d-graphics = "0.8.0"
pistoncore-glutin_window = "0.12.0"
piston2d-opengl_graphics = "0.10.0"
rand = "0.3"
sdl2 = "0.5"
