[package]
name = "rocket"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]

[dependencies]
itertools = "0.3"
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
rand = "0.3"
sdl2 = "0.5"
