[package]
name = "rocket"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]

[dependencies]
piston = "0.3"
piston2d-graphics = "0.4"
pistoncore-glutin_window = "0.4"
piston2d-opengl_graphics = "0.4"
